version: "3.8"
services:
  backend:
    build: .
    ports: ["8000:8000"]
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]